#!/bin/bash
#SBATCH -N 10
#SBATCH --ntasks-per-node=48
#SBATCH --job-name=Re10k
#SBATCH --error=err.out
#SBATCH --output=out.out
#SBATCH --time=48:00:00
#SBATCH --partition=standard

export I_MPI_PIN_DOMAIN=node
export OMP_NUM_THREADS=48

cd /scratch/debartha/3dmurali/runs/Re10k/run2
module load compiler/intel/2020.2.254

mpirun -ppn 1 -np 10 ./AI_9bld5_omp < input | tee out
